openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: Localhost development usage
    url: http://localhost:8080

info:
  version: 1.0.0
  title: Torrent file endpoint
  # put the contact info for your development or API team
  contact:
    email: rugal.bernstein.0@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
#  ----------------------------------------------------------

# tags are used for organizing operations
tags:
- name: post
  description: 
- name: torrent
  description: 
- name: user
  description: 
- name: tag
  description: 

#  ----------------------------------------------------------

components:
  securitySchemes:
    # DO NOT CHANGE THE NEXT LINE
    bearerAuth:
    # DO NOT CHANGE THE PREVIOUS LINE
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    #  --------------------------------basic
    Response204:
      description:  Resource deleted
    Response400:
      description:  Bad request
    Response401:
      description:  Request not authenticated
    Response403:
      description:  Request not authorized
    Response404:
      description:  Resource not found
    Response405:
      description:  Request method not found
    Response406:
      description:  Response representation not negotiable
    Response409:
      description:  Resource conflicted

#  ----------------------------------------------------------

paths:
#  --------------------------------post
  /post/{pid}/torrent:
    parameters:
      - in: path
        name: pid
        description: Post Id
        required: true
        schema:
          type: integer
    post:
      security:
        - bearerAuth: []
      tags:
        - post
        - torrent
      summary: Upload torrent for post
      operationId: upload
      description: Upload torrent file for post by multipart. Will update `hash` field.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                # name it by `file` as the codegen generate no other than `file`
                # this may be a bug of openapi codegen but let do it for now
                file:      
                  type: string
                  format: binary

      responses:
        201:
          description: Torrent file uploaded
        400:
          $ref: '#/components/schemas/Response400'
        401:
          $ref: '#/components/schemas/Response401'
        403:
          $ref: '#/components/schemas/Response403'
        405:
          $ref: '#/components/schemas/Response405'
        406:
          $ref: '#/components/schemas/Response406'
        409:
          $ref: '#/components/schemas/Response409'
    get:
      security:
        - bearerAuth: []
      tags:
        - post
        - torrent
      summary: Download torrent for post
      operationId: download
      description: Download torrent file for post by multipart.
      responses:
        200:
          description: Torrent got
          content:
            application/x-bittorrent:
              schema:
                type: string
                format: binary
        401:
          $ref: '#/components/schemas/Response401'
        403:
          $ref: '#/components/schemas/Response403'
        404:
          $ref: '#/components/schemas/Response404'
        405:
          $ref: '#/components/schemas/Response405'
        406:
          $ref: '#/components/schemas/Response406'
#  ----------------------------------------------------------
